### ISSUE TITLE
Required software updates issues 

### ISSUE THREAD

**Issue by Coope431** [gabides/capacitor-sample-app-sync-issue#1]
After the updates and After the restart. Some contacts and the searchable information is not in my contacts list. I'm mainly using the Contacts app. The missing information doesn't restore from the backup  systems.  Is this normal or is this associated with 'npjason' and the capacitor after echo after app stated.

**Comment by gabides** [comment]
@Coope431 i am not sure what you are trying to do wit this repo, it's a reproduction repo for an issue with Capacitor and is not linked to contacts
